apiVersion: batch/v1
kind: CronJob
metadata:
  name: throw-dice-job
spec:
  schedule: ""
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      backoffLimit: 25
      template:
        spec:
          containers:
            - name: math-add
              image: kodekloud/throw-dice
          restartPolicy: Never
