apiVersion: v1
kind: Pod
metadata:
  name: lion
spec:
  containers:
  - args:
    - -cpus
    - "1"
    image: vish/stress
    name: cpu-stress
    resources:
      limits:
        cpu: "20"
      requests:
        cpu: "2"