apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - env:
    - name: LOG_HANDLERS
      value: file
    image: kodekloud/event-simulator
    name: event-simulator
    volumeMounts:
      - mountPath: /log
        name: webapp
  volumes:
    - name: webapp
      hostpath:
        path: /var/log/webapp
        type: Directory
