apiVersion: v1
kind: Pod
metadata:
  labels:
    name: simple-webapp
  name: simple-webapp-1
spec:
  containers:
    - name: simple-webapp-1
      container:
        image: kodekloud/webapp-delayed-start
        imagePullPolicy: Always
        name: simple-webapp-1
        ports:
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 1