apiVersion: v1
kind: Pod
metadata:
  labels:
    name: simple-webapp
  name: simple-webapp-2
spec:
  containers:
    - name: simple-webapp
      container:
        image: kodekloud/webapp-delayed-start
        imagePullPolicy: Always
        name: simple-webapp
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 8080