apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-dashboard
spec:
  template:
    metadata:
      labels:
        name: web-dashboard
    spec:
      containers:
      - image: kodekloud/my-kubernetes-dashboard
        imagePullPolicy: Always
        name: web-dashboard
        ports:
        - containerPort: 8080
          protocol: TCP
      serviceAccount: dashboard-sa