apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  template:
        metadata:
         labels: 
            run: nginx
        spec:
          containers:
            - name: nginx
              image: nginx
          affinity:
            nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                        - matchExpressions:
                            - key: name
                              operator: In
                              values:
                                - blue
  replicas: 6
  selector:
    matchLabels:
      run: nginx